"""init

Revision ID: 100b56aa05ba
Revises: 
Create Date: 2024-03-16 23:16:12.960802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '100b56aa05ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.VARCHAR(), nullable=False),
    sa.Column('sender', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_chat_id'), 'chat', ['chat_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', postgresql.ENUM('user', 'admin', 'todo_owner', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('friend_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.VARCHAR(), nullable=False),
    sa.Column('receiver_name', sa.VARCHAR(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'accepted', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_name'], ['user.username'], ),
    sa.ForeignKeyConstraint(['sender_name'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friend_request_id'), 'friend_request', ['id'], unique=False)
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(), nullable=False),
    sa.Column('friend_name', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['friend_name'], ['user.username'], ),
    sa.ForeignKeyConstraint(['user_name'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friendship_id'), 'friendship', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friendship_id'), table_name='friendship')
    op.drop_table('friendship')
    op.drop_index(op.f('ix_friend_request_id'), table_name='friend_request')
    op.drop_table('friend_request')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_chat_chat_id'), table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###
