"""0_9_rename chat->title

Revision ID: 2336ca011102
Revises: 2de2026f64cd
Create Date: 2024-05-03 23:48:01.219245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2336ca011102'
down_revision: Union[str, None] = '2de2026f64cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE chat RENAME COLUMN chat TO title")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('chat', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_chat_title'), table_name='chat')
    op.create_index('ix_chat_chat', 'chat', ['chat'], unique=True)
    op.drop_column('chat', 'title')
    # ### end Alembic commands ###
