"""0_8

Revision ID: 2de2026f64cd
Revises: d8d0f12a55c6
Create Date: 2024-05-03 23:10:12.972850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2de2026f64cd'
down_revision: Union[str, None] = 'd8d0f12a55c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('status', postgresql.ENUM('user', 'admin', 'moder', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_users', sa.Column('status', postgresql.ENUM('user', 'admin', 'moder', name='role'), autoincrement=False, nullable=False))
    op.drop_table('group')
    # ### end Alembic commands ###
