"""Noti-Mes-Fri

Revision ID: 52fb14ffde71
Revises: e33645bcd5a9
Create Date: 2024-04-05 22:32:03.887670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52fb14ffde71'
down_revision: Union[str, None] = 'e33645bcd5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificationFriend',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('friend_request_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['friend_request_id'], ['friend_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificationFriend_id'), 'notificationFriend', ['id'], unique=False)
    op.create_table('notificationMessage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificationMessage_id'), 'notificationMessage', ['id'], unique=False)
    op.drop_index('ix_notification_id', table_name='notification')
    op.drop_table('notification')
    op.drop_index('ix_chat_chat', table_name='chat')
    op.create_index(op.f('ix_chat_chat'), 'chat', ['chat'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_chat'), table_name='chat')
    op.create_index('ix_chat_chat', 'chat', ['chat'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('friend_request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['friend_request_id'], ['friend_request.id'], name='notification_friend_request_id_fkey'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='notification_message_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='notification_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notification_pkey')
    )
    op.create_index('ix_notification_id', 'notification', ['id'], unique=False)
    op.drop_index(op.f('ix_notificationMessage_id'), table_name='notificationMessage')
    op.drop_table('notificationMessage')
    op.drop_index(op.f('ix_notificationFriend_id'), table_name='notificationFriend')
    op.drop_table('notificationFriend')
    # ### end Alembic commands ###
