"""add username messDB

Revision ID: d8d0f12a55c6
Revises: 4b33c92b1fed
Create Date: 2024-04-16 22:21:22.087827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8d0f12a55c6'
down_revision: Union[str, None] = '4b33c92b1fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('sender_username', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'sender_username')
    # ### end Alembic commands ###
